main/urls.py
from django.urls import path
from .views import *
app_name = "mail"
urlpatterns = [
    path('', index, name="index"),
    path('mail/', mail, name="mail"),
    path('id/<str:id>', id, name="id"),
    path('sent/<int:pk>', sent, name="sent"),

]

main/models.py
from datetime import datetime, timezone
from django.db import models

# Create your models here.


class Id(models.Model):
    unique_id = models.CharField(max_length=100)
    time_created = models.DateTimeField(default=datetime.now(tz=timezone.utc))
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=30)
    mail = models.CharField(max_length=100)
    mail_is_real = models.BooleanField(default=False, blank=False)
    ip = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"ID - {self.unique_id}\n TIME - {self.time_created}"


class User(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=30)
    mail = models.CharField(max_length=100)

main/views.py
from django.shortcuts import render, redirect
from .mail import *
from .db import *
from .models import *
from django.db.utils import IntegrityError


def index(request):
    check_if_key_is_valid(Id)
    return render(request, 'main/index.html')


def mail(request):
    check_if_key_is_valid(Id)
    if request.method == "POST":
        if verifymail(request.POST['mail']):
            ip = request.META.get('REMOTE_ADDR', None)
            import uuid
            id = Id.objects.create()
            id.unique_id = uuid.uuid4()
            id.ip = ip
            name = request.POST['name']
            mail = request.POST['mail']
            username = request.POST.get('username')

            for item in Id.objects.all():
                if item.mail == mail:
                    return render(request, 'main/index.html', context={"error": "You have already registered"})
                else:
                    pass
            try:
                id.mail = mail
                id.name = name
                id.username = username
            except IntegrityError:
                return render(request, 'main/index.html', context={"error": "You have already registered"})
            id.save()
            return redirect('mail:sent', id.pk)
        else:
            return render(request, 'main/index.html', context={"error": "Provide a valid mail"})
    else:
        return render(request, 'main/error.html', context={"error": "Invalid Method"})


def id(request, id):
    check_if_key_is_valid(Id)
    for i in Id.objects.all():
        if id in i.unique_id:
            try:
                global valid
                valid = True
            except (Id.DoesNotExist, KeyError):
                valid = False
        elif id not in i.unique_id:
            valid = False
    if valid == False:
        return render(request, 'main/id.html', context={"id": "Session Expired/ID not valid"})
    elif valid == True:
        crr_id = Id.objects.get(unique_id=id)
        user = User.objects.create()
        user.mail = crr_id.mail
        user.name = crr_id.name
        user.username = crr_id.username
        crr_id.mail_is_real = True
        crr_id.save()
        user.save()
        return render(request, 'main/id.html', context={"id": crr_id})


def sent(request, pk):
    check_if_key_is_valid(Id)
    id = Id.objects.get(pk=pk)
    mail = id.mail
    from .mail import send__mail
    send__mail(pk, mail)
    return render(request, 'main/sent.html', context={"id": id})

templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script src="{% static 'index.js' %}"></script>
  </head>
  <body class="bg bg-light">
    {% block body %}{% endblock body %}
  </body>
</html>

templates/index.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UNDER DEVELOPMENT</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <style>
      body {
        padding: 5%;
      }
    </style>
  </head>
  <body class="bg bg-light">
    <h1 class="text text-primary">This site is currently under DEVELOPMENT</h1>
  </body>
</html>

templates/main/error.html
{% extends 'base.html' %}
{% block title %}Error{% endblock title %}
{% block body %}
<div class="alert alert-danger"> <h1>{{ error }}</h1> </div>
{% endblock body %}

templates/main/id.html
{% extends 'base.html' %} 
    {% block title %}Check your id{% endblock title %}
    {% block body %}
        <h2 class="text-success">Hi, {{id.name}}</h2>
        <h1 class="text-center text-primary">You have been successfully registered</h1>

    {% endblock body %}

templates/main/index.html
{% extends 'base.html' %}
{% block title %}Enter Your mail{% endblock title %}
{% block body %}
{% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <body class="bg bg-light">
    {% if error %}
    <h2 class="alert alert-danger">{{ error }}</h2>
    {% endif %}
    <form method="POST" action="{% url 'mail:mail' %}">
      {% csrf_token %}
    <h2 id="gh"class="text-primary">Welcome</h2>  
      <input class="form-control" type="email" name="mail" placeholder="Email"  required/>
      <br>
      <input name="name" class="form-control" type="text" placeholder="Name" required>
      <br>
      <input type="text" class="form-control" name="username" placeholder="Username(Optional)" option>
      <br>
      <button class="btn btn-primary" type="submit">Send mail</button>
    </form>
  </body>
</html>

{% endblock body %}

templates/main/sent.html
{% extends 'base.html' %}
{% block title %}
Mail Sent
{% endblock title %}
{% block body %}
<h1 class="text-primary">Mail Has been sent</h1>
<h6 style="display:none;">{{ id }}</h6>
{% endblock body %}